services:
    aircode.autocomplete.controller:
        class: aircode\autocomplete\controller\autocomplete
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'